### ISSUE TITLE
Compilation error: MSP.h: No such file or directory

### ISSUE THREAD

**Issue by simranjeetsingh21** [ramiss/arduino_DJI_03_RC_ARM#24]
Hello Ramiss,
I am new in this and I am just following the instructions given buy you on RC arm.
there is an error and I have no idea how to solve this.

C:\Users\simranjeet singh\Desktop\arduino_DJI_03_RC_ARM-main\arduino_DJI_03_RC_ARM\arduino_DJI_03_RC_ARM.ino:28:10: fatal error: MSP.h: No such file or directory
 #include "MSP.h"
          ^~~~~~~
compilation terminated.

exit status 1

Compilation error: MSP.h: No such file or directory

**Comment by ramiss** [comment]
See step 2, you need to download the entire repository:

![image](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/2555410/7677ea66-1751-46fe-bc0e-f63134a6a440)

**Comment by simranjeetsingh21** [comment]
I did same but still give me the same error

**Comment by ramiss** [comment]
Did you keep everything on the exact same file structure?

**Comment by simranjeetsingh21** [comment]
exactly same file structure

**Comment by simranjeetsingh21** [comment]
is there some thing else can cause this error or just a MSP file ?

**Comment by simranjeetsingh21** [comment]
is it possible to install MSP file separately?

**Comment by ramiss** [comment]
You must not.  See step 2. This version is a custom version

**Comment by ramiss** [comment]
Send me a screenshot of your folder structure

**Comment by simranjeetsingh21** [comment]
![Screenshot 2024-01-04 190521](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/155690598/e58f4a52-6326-4e30-8225-87a95c88b9de)
![Screenshot 2024-01-04 190701](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/155690598/1f7d96b6-b6e6-4126-af7c-4ebf990d3378)
![Screenshot 2024-01-04 190803](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/155690598/934c34d6-32df-4f7e-bf89-0a1fc6280959)
![Screenshot 2024-01-04 190854](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/155690598/4cec6f57-3f82-4f1c-aad5-fa7658019426)

**Comment by simranjeetsingh21** [comment]
did I send you the right things that you want to see?

**Comment by ramiss** [comment]
No.  I'm talking about the folder structure on the computer.  All of the files need to be in the same folder, like you see them in the GitHub repository.

**Comment by simranjeetsingh21** [comment]
![Screenshot 2024-01-04 200340](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/155690598/718438da-7238-4068-bedd-c2ff8ac67f69)

**Comment by simranjeetsingh21** [comment]
one more question when I choose to upload files the only first file " arduino_DJI-O3_RC_ARM" is shown in the folder not the rest of others you can see in the attached photo. Is it supposed to be like that?
![Screenshot 2024-01-04 200828](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/155690598/d7bfcec9-2970-4159-903d-dba61c27e455)

**Comment by ramiss** [comment]
I see your issue.  
1. Create a folder on your computer called "arduino_DJI_03_RC_ARM"   exactly that name, no "-main" or anything else.
2. Then put all of the files into that folder.
3. Open the arduino_DJI_03_RC_ARM.ino file from that folder.

**Comment by simranjeetsingh21** [comment]
you are the great MAN, finally it is uploaded
so now if I connect it with DJI O3 air unit it will automatically goes to full power mode or there are some other steps?

**Comment by ramiss** [comment]
Yes,  after two seconds of power the air unit will arm (if wired correctly).

**Comment by simranjeetsingh21** [comment]
I hope i ll give you good news

**Comment by dennisjules** [comment]
Hi Ramiss, 
First of all, thanks a lot for sharing this and to those who contributed, it worked perfectly. 
Curious if you have steps to arm O3 via flight controller coz im planning to setup with gps and osd.
Thanks again.

**Comment by ramiss** [comment]
> Hi Ramiss, First of all, thanks a lot for sharing this and to those who contributed, it worked perfectly. Curious if you have steps to arm O3 via flight controller coz im planning to setup with gps and osd. Thanks again.

Hello.  Glad it worked for you.  That said,  if you use a flight controller then the Arduino becomes redundant,  in fact you shouldn't use them together.  The flight controller will send the arm command and the OSD from the GPS etc.    This android project was only devised for those that didn't want to bother with a flight controller.

**Comment by dennisjules** [comment]
Agree on using either of them but what I mean is, how to arm the O3 using flight controller not by arduino. Mads tech youtuber mentioned that turning off the low power mode in goggles does not arm the O3 thereby we cannot use O3 at full power. Not sure if this is true nowadays.

**Comment by ramiss** [comment]
The 03 automatically goes into full power mode once it sees the arm signal from the flight controller (which this arduino project simply mimics).   For a flight controller, you hook up the RX/TX (or S-BUS) to the flight controller and then configure the flight controller so that it knows the 03 is on that port.  You then tell the flight controller to arm using a switch on your transmitter. How you do all of that depends entirely on which firmware you are using (betaflight, iNav, Ardupilot etc).  Without any more info I can't offer any more instruction.

**Comment by abritten** [comment]
Hi @ramiss thanks again for your efforts. Regarding a general flight controller arming, or your SAMD21 arming the O3, I currently use both because my flight controller is actually a Teensy arduino and is using a open source code DrehmFlight. So I have your SAMD21 arming the O3 becasue my Teensy is not capable of doing it (lacking code). However because the Teensy Drehmflight is written in Arduino, I was hoping to copy your code and try to get the Teesny to replace the SAMD21 and arm the O3 solely by itself. But I am not a solid programmer, nor do I fully understand the structure of your MSP files. Would this be a project you would like to work on with me? So it would be a similar repo as this SAMD21 version, but the Teensy version. Drehmflight is becoming more popular with the hobbyist drone community because of its VTOL simplicity and customizing capabilities that Betaflight and Ardupilot cannot accomplish. I think getting the O3 hacked with the Teensy Drehmflight would be an awesome contribution if you want to help make it happen!

**Comment by ramiss** [comment]
Hi @abritten - I'm honored to be asked to contribute, but I simply don't have the time.  You would only need to incorporate the code within my .ino file into your own code.  All of the other files can simply be included.

**Comment by dennisjules** [comment]
> The 03 automatically goes into full power mode once it sees the arm signal from the flight controller (which this arduino project simply mimics). For a flight controller, you hook up the RX/TX (or S-BUS) to the flight controller and then configure the flight controller so that it knows the 03 is on that port. You then tell the flight controller to arm using a switch on your transmitter. How you do all of that depends entirely on which firmware you are using (betaflight, iNav, Ardupilot etc). Without any more info I can't offer any more instruction.

@ramiss Currently I’m using below setup
HGLRC Zeus F722 flight controller and using betaflight 4.4, I did not setup any AUX under MODES section in BF.
Radiolink RC6GS radio
Radiolink R7FG receiver with gyro enabled
Dji O3 unit
Dji goggles 2 with low power mode disabled
BKRC head tracker
Everything is working fine and in my goggles I see the OSD I needed and 50mbps on my video signal but the moment I turn it on, it is not auto recording compared with your arduino setup.
My question is, with that 50mbps video signal is it right to assume that my O3 unit is in arm state without setting anything inside betaflight?  If the answer is no, how can I set it up in BF to arm my O3 but do I need to arm considering the 50mbps?
Because from youtuber mads tech that 50mbps doesn’t mean the O3 is armed just by disabling low power state, so we cannot use the full power of O3 unless we send an arm command to O3. So this is what I’m trying to find out. Thanks.

**Comment by ramiss** [comment]
@dennisjules if you see the custom OSD and 50mbps then the 03 is at full power.  You either need to enable the record on arm setting and/or your SD card is full.

**Comment by dennisjules** [comment]
> @dennisjules if you see the custom OSD and 50mbps then the 03 is at full power. You either need to enable the record on arm setting and/or your SD card is full.

That’s what I thought but I compared the arduino versus my FC setup. Arduino range is farther so that means my FC setup although seeing 50mbps was not indeed using it’s full power since it is not arm as mads tech mentioned in his youtube video. So finding ways now on how to arm O3 unit under FC setup.

**Comment by abritten** [comment]
> > @dennisjules if you see the custom OSD and 50mbps then the 03 is at full power. You either need to enable the record on arm setting and/or your SD card is full.
> 
> That’s what I thought but I compared the arduino versus my FC setup. Arduino range is farther so that means my FC setup although seeing 50mbps was not indeed using it’s full power since it is not arm as mads tech mentioned in his youtube video. So finding ways now on how to arm O3 unit under FC setup.

I tested the power consumption for the 03 air unit on a power supply, arming it via a Betaflight FC and then SAMD21. Both had equal power consumption:

Standby = 4.5W
Armed = ~11W

**Comment by dennisjules** [comment]
> > > @dennisjules if you see the custom OSD and 50mbps then the 03 is at full power. You either need to enable the record on arm setting and/or your SD card is full.
> 
> > 
> 
> > That’s what I thought but I compared the arduino versus my FC setup. Arduino range is farther so that means my FC setup although seeing 50mbps was not indeed using it’s full power since it is not arm as mads tech mentioned in his youtube video. So finding ways now on how to arm O3 unit under FC setup.
> 
> 
> 
> I tested the power consumption for the 03 air unit on a power supply, arming it via a Betaflight FC and then SAMD21. Both had equal power consumption:
> 
> 
> 
> Standby = 4.5W
> 
> Armed = ~11W

What you mean by power consumption? The RF output?

**Comment by borisbl4** [comment]
![1000069520.jpg](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/110538252/9c7483f5-cfb9-494b-a87a-70af8cff80b3)
![1000070070.jpg](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/110538252/45f81eb9-89d6-4a26-90c8-8e69be11dab1)

Hello, I'm trying to upgrade to a different version of the board.  I don’t quite understand this. There is a mistake.

![1000070071.jpg](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/110538252/1794e934-dca8-4bea-aae1-2fc93e671bfd)

D:\Загрузки\arduino_DJI_03_RC_ARM\arduino_DJI_03_RC_ARM.ino: In function 'void setup()':
D:\Загрузки\arduino_DJI_03_RC_ARM\arduino_DJI_03_RC_ARM.ino:87:3: error: 'analogReadResolution' was not declared in this scope; did you mean 'analogWriteResolution'?
D:\Загрузки\arduino_DJI_03_RC_ARM\arduino_DJI_03_RC_ARM.ino: In function 'void debugPrint()':
D:\Загрузки\arduino_DJI_03_RC_ARM\arduino_DJI_03_RC_ARM.ino:334:3: error: 'SerialUSB' was not declared in this scope; did you mean 'Serial1'?

exit status 1

Compilation error: 'analogReadResolution' was not declared in this scope; did you mean 'analogWriteResolution'?

**Comment by ramiss** [comment]
SerialUSB is depreciated in later board libraries, which is why the Seeeduino instructions specify to use an older board "version".   You could try try lowering the board version for your board or investigate the replacement code, which I believe is just replacing with the specific SerialX function.  

You could also safely comment out the Serialxxx.Print line(s) as that just spits out debug code, but I would keep it if you are experimenting with a new board.

And.. the ESP8266 doesn't need the analogReadResolution as it only has 10-bit (hence the error), so you need to remove or comment out that line.

**Comment by dennisjules** [comment]
@ramiss Tested again today
Using FC at 50mbps but video signal drop at 1 bar at 100meters
Using arduino no video signal drop at 350meters
Therefore I can confirmed using FC doesn't arm O3 unit eventhough you disable low power mode and at 50mbps.

**Comment by ramiss** [comment]
Appologies, but without more information on your setup I can't diagnose it. Also,  just pointing out that you are asking in literally the opposite location.  You should find the forum for that flight controller or firmware ;)

**Comment by dennisjules** [comment]
@ramiss no worries, I'm just sharing my experience in case somebody reads this thread. There was a lot of confusion from other threads that using an FC will arm the O3 unit when we disabled the low power mode but it's not the case. As mentioned before, I'm looking now for an auto arm feature in Betaflight. For now the only way I can do that is to use my dji fpv radio controller. Just curious though, can you share which portion in the arduino code that arms the O3. Thanks 🙏🏼

**Comment by ramiss** [comment]
> can you share which portion in the arduino code that arms the O3. Thanks 🙏🏼

There's not a whole lot of fluff in the code.   The arm command is below, but that is pulling configuration data from the other variables and structures, and sending through the MSP library.  

```
//MSP_STATUS
  status_DJI.flightModeFlags = flightModeFlags;
  status_DJI.armingFlags = 0x0303;
  msp.send(MSP_STATUS_EX, &status_DJI, sizeof(status_DJI));
  status_DJI.armingFlags = 0x0000;
  msp.send(MSP_STATUS, &status_DJI, sizeof(status_DJI));
```

**Comment by ismail3887** [comment]
Hello, I do as you explained in the article and diagram, but I still get errors. Can you make a short video about this topic? Or can someone who has done this help me on this issue? I've been trying for 2 days but I can't do it.

**Comment by ramiss** [comment]
Please post your errors.

**Comment by ismail3887** [comment]
> Please post your errors. 

Doesn't it work when the power input to seediuno is supplied with 5v BEC? I didn't understand the seeediuno (any receive channel for power) part. Do I need to connect it to the + and - part of any input channel on the receiver?![image](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/58310410/4ad59155-21b7-4cd5-a7ef-3ac63239e223)

**Comment by dennisjules** [comment]
@ismail3887 
Seeeduino can be powered by any power source as long as it is DC 5v nothing more. I powered my seeeduino from my receiver channel/aux(RX) and everything works great.

**Comment by ismail3887** [comment]
> Seeeduino can be powered by any power source as long as it is DC 5v nothing more. I powered my seeeduino from my receiver channel and everything works great.

Did you do it like in the photo? Can we please talk on a platform that will communicate with me faster? With Instagram or any five social media. I need to solve it as soon as possible @dennisjules

**Comment by dennisjules** [comment]
![image](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/157116897/d160d865-96db-4f97-9a81-731220dec74b)

Don't confuse yourself with the other wires coz I have 2 setup in parallel. One using FC and the other one using seeeduino.

**Comment by ismail3887** [comment]
> ![image](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/157116897/d160d865-96db-4f97-9a81-731220dec74b)

Can you write me on Instagram? ( @ismail_fpv )

**Comment by ismail3887** [comment]
> Please post your errors. 

Did I manage to install the software?![image](https://github.com/ramiss/arduino_DJI_03_RC_ARM/assets/58310410/505d9cb6-e729-4984-a133-7316ee5b74be)

Possible causes:
- Selected Bootloader version does not match the one on Bluefruit device.
    Please upgrade the Bootloader or select correct version in Tools->Bootloader.
- Baud rate must be 115200, Flow control must be off.
- Target is not in DFU mode. Ground DFU pin and RESET and release both to enter DFU mode.

**Comment by ramiss** [comment]
@ismail3887 - You literally posted your answer.  Software did not install, follow the directions under possible causes.  Also, make sure you are set to the proper serial port.  If you are still having issues then go watch other tutorials on the basics of Arduinos.

**Comment by ismail3887** [comment]
> @ismail3887 - You literally posted your answer.  Software did not install, follow the directions under possible causes.  Also, make sure you are set to the proper serial port.  If you are still having issues then go watch other tutorials on the basics of Arduinos.

Is the correct serial port as seen in the photo? Is everything correct?

**Comment by ramiss** [comment]
@ismail3887. It depends on your computer setup.  Please read about arduino basics and then try again. 
https://www.digikey.com/en/maker/tutorials/2018/how-to-get-started-with-arduino
